remote_theme: daviddarnes/alembic@main
plugins:
- jekyll-remote-theme

title: Electronic Component Recognizer
description: An image classification API that classifies 20 different types of electronic components commonly used in circuits and devices

author:
  name: Md Faisal Ahmed
